# left-side user profile
# avatar: # by default https://octodex.github.com/images/baracktocat.jpg
avatar: https://www.gravatar.com/avatar/099703df237acafd6c3b962721f959d7.jpg?s=200
location:
email: lightjiao@gmail.com
social:
  github: https://github.com/lightjiao
  weibo:
  linkedin:

# navbar menu
menu:
  archives: true
  tags: true
  categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gcs: # google custom search code

# flagcounter
flagcounter_href: # https://info.flagcounter.com/xxxx
flagcounter_img_src: # https://s01.flagcounter.com/xxxx

# article_edit 在文章页显示跳转到编辑页
article_edit:
  enable: false #是否启用
  prefix: https://github.com/xxx/xxx/edit/master/source/ #编辑页前缀
