name: Hexo GitHub Actions
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Setup
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          TZ: Asia/Shanghai
        run: |
          # set up private key for deploy
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # set git information
          git config --global user.name 'lightjiao@github'
          git config --global user.email 'lightjiao@gmail.com'

          # prepare blog
          # pip install -r requirements.txt
          # python blog.py prepare

          # install dependencies
          npm install -g hexo-cli
          npm install
    
      - name: Deploy
        run: |
          # publish my blog
          hexo clean
          hexo generate
          hexo deploy